# Generated by Django 4.2.6 on 2025-07-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationcode',
            name='code',
            field=models.CharField(default='lU0Co_WUbLLbLDsQ5XtI', max_length=20),
        ),
    ]
