# Generated by Django 4.2.6 on 2024-08-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type_users',
            field=models.CharField(blank=True, choices=[('SP', 'ServiceProvider'), ('SC', 'ServiceConsumer')], max_length=5, null=True),
        ),
    ]
