# Generated by Django 4.2.6 on 2025-07-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_emailverificationcode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationcode',
            name='code',
            field=models.CharField(default='KzN4b_Pyz8Z44ZTz_PkZ', max_length=20),
        ),
    ]
