# Generated by Django 4.2.6 on 2024-08-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_type_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
    ]
