# Generated by Django 4.2.6 on 2025-07-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_emailverificationcode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationcode',
            name='code',
            field=models.CharField(default='qNk-e8aZDrFSCHxzQZuR', max_length=20),
        ),
    ]
