# Generated by Django 4.2.6 on 2025-07-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_emailverificationcode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationcode',
            name='code',
            field=models.CharField(default='cjto_coxR0BGUu-aYOVg', max_length=20),
        ),
    ]
