# Generated by Django 4.2.6 on 2025-07-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_email_alter_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationcode',
            name='code',
            field=models.CharField(default='AVvc3e1MgDa-39Kiq9xf', max_length=20),
        ),
    ]
