# Generated by Django 4.2.6 on 2025-11-12 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SatusInvoice',
            new_name='StatusInvoice',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='satus',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='productId',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='quintity',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='invoiceId',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='updated_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_invoices', to=settings.AUTH_USER_MODEL),
        ),
    ]
