# Generated by Django 5.2.4 on 2025-07-24 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.AddField(
            model_name='product',
            name='main_unit',
            field=models.ForeignKey(blank=True, limit_choices_to={'unit_type': 'MA'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_unit_products', to='product.unit'),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_unit',
            field=models.ForeignKey(blank=True, limit_choices_to={'unit_type': 'SU'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_unit_products', to='product.unit'),
        ),
        migrations.AddField(
            model_name='unit',
            name='parent_unit',
            field=models.ForeignKey(blank=True, limit_choices_to={'unit_type': 'MA'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_units', to='product.unit'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_units', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='unit',
            name='updated_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_units', to=settings.AUTH_USER_MODEL),
        ),
    ]
