# Generated by Django 4.2.6 on 2026-01-05 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_initial'),
        ('product', '0004_remove_product_unit_product_main_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_by_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='private_products', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=180, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='lessAmount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
