# Generated by Django 4.2.6 on 2026-01-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_created_by_shop_product_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='note',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
