# Generated by Django 4.2.6 on 2026-01-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_customershop_alter_productshop_lessamount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productshop',
            name='note',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
